# how many players do u want
restPlayers: 3
# not implemented yet
bossPlayers: 1
# GameDuration in seconds
gameDuration: 120
shutdownCountdown: 30
LobbyWorld: 'lobby'
spawnLocation: '0,4,0'
GameWorld: 'arena'
BossTeamName: 'chaser mamalon'
RestPlayersTeamName: 'bola de jotos'
