# how many players do u want
restPlayers: 3
# not implemented yet
bossPlayers: 1
# GameDuration in seconds
gameDuration: 120
LobbyWorld: 'lobby'
spawnLocation: '0,4,0'
GameWorld: 'arena'
BossTeamName: 'Boss'
RestPlayersTeamName: 'Rest'
